name: Python CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (before Docker)
        run: |
          pytest tests/

      - name: Build Docker image
        run: |
          docker build -t my-python-cli .

      - name: Run tests inside Docker container
        run: |
          docker run --rm my-python-cli pytest tests/
